# Generated by Django 5.1.2 on 2024-10-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_customuser_activate_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn_company',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_company',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='ОГРН'),
        ),
    ]
