# Generated by Django 5.1.2 on 2024-10-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_alter_customuser_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Сроки')),
            ],
            options={
                'verbose_name': 'Проваленные отчеты',
                'verbose_name_plural': 'Проваленные отчеты',
                'db_table': 'failed_reports',
            },
        ),
        migrations.CreateModel(
            name='Overdue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Просрочка')),
            ],
            options={
                'verbose_name': 'Просрочка',
                'verbose_name_plural': 'Просрочка',
                'db_table': 'overdue',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='block_contractor',
            field=models.BooleanField(default=False, verbose_name='Заблокировать подрядчика. Для подрядчика'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='block_sending_report',
            field=models.BooleanField(default=False, verbose_name='Заблокировать отправку  отчето. Для подрядчика'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='creating_prescriptions',
            field=models.BooleanField(default=False, verbose_name='Создание предписаний. Для Сотрудники'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='penalty',
            field=models.BooleanField(default=False, verbose_name='Штраф. Для подрядчика'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='processing_orders',
            field=models.BooleanField(default=False, verbose_name='Обработка предписаний. Для Сотрудники'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='report_processing',
            field=models.BooleanField(default=False, verbose_name='Обработка отчетов. Для Сотрудники'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authen.failedreports', verbose_name='Проваленные отчеты. Для подрядчика'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='overdue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authen.overdue', verbose_name='Просрочка. Для подрядчика'),
        ),
    ]
