# Generated by Django 5.1.2 on 2024-10-15 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_failedreports_overdue_customuser_block_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='authen.company', verbose_name='Компания'),
        ),
    ]
