# Generated by Django 5.1.2 on 2024-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_alter_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'required': 'Электронная почта обязателен для заполнения.'}, max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
