# Generated by Django 5.1.2 on 2024-10-19 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_prescriptionsuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='contractor',
        ),
        migrations.DeleteModel(
            name='PrescriptionsUser',
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подрядчик'),
        ),
    ]
