# Generated by Django 5.1.2 on 2024-10-23 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_alter_prescriptions_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='contractor',
        ),
        migrations.CreateModel(
            name='PrescriptionContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'В обработке'), (3, 'Устранено'), (4, 'Просрочено'), (5, 'Null')], default=1, verbose_name='Статус для подрядчика')),
                ('deadline', models.DateField(verbose_name='Срок устранения для подрядчика')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Подрядчик')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_statuses', to='prescription.prescriptions')),
            ],
            options={
                'unique_together': {('prescription', 'contractor')},
            },
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='contractors',
            field=models.ManyToManyField(related_name='contractor_prescriptions', through='prescription.PrescriptionContractor', to=settings.AUTH_USER_MODEL, verbose_name='Подрядчики'),
        ),
    ]
