# Generated by Django 5.1.2 on 2024-10-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0009_alter_prescriptions_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_prec', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
