# Generated by Django 5.1.2 on 2024-10-16 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Раздел',
                'db_table': 'bob',
            },
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Тип работ',
                'verbose_name_plural': 'Тип работ',
                'db_table': 'type_work',
            },
        ),
        migrations.CreateModel(
            name='ReportsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название отчета')),
                ('constructor_accepted', models.BooleanField(default=False, verbose_name='Принял подрядчики')),
                ('accepted_customer', models.BooleanField(default=False, verbose_name='Принято сотрудники')),
                ('expired_customer', models.BooleanField(default=False, verbose_name='Истекший сотрудники/подрядчики')),
                ('expired_admin', models.BooleanField(default=False, verbose_name='Истекший администратора')),
                ('status', models.IntegerField(choices=[(1, 'В обработке'), (2, 'Принят'), (3, 'Отказ')], default=1, verbose_name='Статус администратора')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Администратора')),
                ('constructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructor', to=settings.AUTH_USER_MODEL, verbose_name='Подрядчики')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчеты',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='RespostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('repost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respost_comment', to='report_app.reportsname', verbose_name='Отчеты')),
            ],
            options={
                'verbose_name': 'Комментарий отчетов',
                'verbose_name_plural': 'Комментарий отчетов',
                'db_table': 'repost_comment',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=250, verbose_name='Позиция')),
                ('quantity', models.CharField(max_length=250, verbose_name='Количество')),
                ('frame', models.CharField(max_length=250, verbose_name='Корпус')),
                ('floor', models.CharField(max_length=250, verbose_name='Этаж')),
                ('mark', models.CharField(max_length=250, verbose_name='Отметка')),
                ('axles', models.CharField(max_length=250, verbose_name='Оси')),
                ('premises', models.CharField(max_length=250, verbose_name='Помещение')),
                ('completions', models.CharField(max_length=250, verbose_name='Завершения')),
                ('files', models.FileField(blank=True, null=True, upload_to='reports_file/', verbose_name='Файл отчетов')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('bob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.bob', verbose_name='Раздел')),
                ('reports_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposts', to='report_app.reportsname', verbose_name='Название отчета')),
                ('type_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report_app.typework', verbose_name='Тип работ')),
            ],
            options={
                'verbose_name': 'Отчеты',
                'verbose_name_plural': 'Отчеты',
                'db_table': 'reports_1',
            },
        ),
    ]
