# Generated by Django 5.1.2 on 2024-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_alter_reportsname_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsname',
            name='status_contractor',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Отправлено'), (3, 'Принято'), (4, 'Отказ')], default=1, verbose_name='Статус подрядчики'),
        ),
        migrations.AlterField(
            model_name='reportsname',
            name='status_customer',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Отправлено'), (3, 'Принято'), (4, 'Отказ')], default=1, verbose_name='Статус сотрудники'),
        ),
    ]
