# Generated by Django 5.1.2 on 2024-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0005_alter_reportsname_status_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsname',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В обработке'), (3, 'Принят'), (4, 'Отказ'), (5, 'Null')], default=5, verbose_name='Статус администратора'),
        ),
        migrations.AlterField(
            model_name='reportsname',
            name='status_contractor',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Отправлено'), (3, 'Принято'), (4, 'Отказ'), (5, 'Null')], default=4, verbose_name='Статус подрядчики'),
        ),
        migrations.AlterField(
            model_name='reportsname',
            name='status_customer',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Отправлено'), (3, 'Принято'), (4, 'Отказ'), (5, 'Null')], default=5, verbose_name='Статус сотрудники'),
        ),
        migrations.AlterField(
            model_name='reportsname',
            name='status_user',
            field=models.IntegerField(choices=[(1, 'Отправлено'), (2, 'Принято'), (3, 'Отказ'), (4, 'Null')], default=4, verbose_name='Статус пользователя'),
        ),
    ]
