# Generated by Django 5.1.2 on 2024-10-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0007_alter_reportsname_status_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='axles',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Оси'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='completions',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Завершения'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='floor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='frame',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='mark',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Отметка'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='premises',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='quantity',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Количество'),
        ),
    ]
