# Generated by Django 5.1.2 on 2024-10-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0008_alter_reports_axles_alter_reports_completions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='files',
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='report_file/', verbose_name='Файлы отчетов')),
                ('report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='report_app.reports', verbose_name='Отчеты')),
            ],
            options={
                'verbose_name': 'Файлы отчетов',
                'verbose_name_plural': 'Файлы отчетов',
                'db_table': 'reports_file',
            },
        ),
    ]
