# Generated by Django 5.1.2 on 2024-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0009_remove_reports_files_reportfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Отчеты информацию', 'verbose_name_plural': 'Отчеты информацию'},
        ),
        migrations.AlterField(
            model_name='reportsname',
            name='status_contractor',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Отправлено'), (3, 'Принято'), (4, 'Отказ'), (5, 'Вернулся')], default=5, verbose_name='Статус подрядчики'),
        ),
    ]
