# Generated by Django 5.1.2 on 2024-10-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0010_alter_reports_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsname',
            name='status_customer',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'Отправлено'), (3, 'Принято'), (4, 'Отказ'), (5, 'Вернулся')], default=5, verbose_name='Статус сотрудники'),
        ),
    ]
