# Generated by Django 5.1.2 on 2024-11-08 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0006_project_contractor'),
        ('report_app', '0011_alter_reportsname_status_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsname',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_account.project', verbose_name='Проект'),
        ),
    ]
