# Generated by Django 5.1.2 on 2024-11-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0012_reportsname_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='unity',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ед.изм'),
        ),
    ]
