# Generated by Django 5.1.2 on 2024-11-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_customuser_summ'),
        ('report_app', '0013_reports_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsname',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authen.company', verbose_name='Компании'),
        ),
    ]
