# Generated by Django 5.1.2 on 2024-10-14 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Проекта статус',
                'verbose_name_plural': 'Проекта статус',
                'db_table': 'project_status',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('opening_date', models.DateField(verbose_name='Дата открытия')),
                ('submission_deadline', models.DateField(verbose_name='Дедлайн по сдаче')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor', to=settings.AUTH_USER_MODEL, verbose_name='Подрядчики')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onwer', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_account.projectstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Проекта',
                'verbose_name_plural': 'Проекта',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image/', verbose_name='Изображение проекта')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='admin_account.project', verbose_name='Проекта')),
            ],
            options={
                'verbose_name': 'Изображение проекта',
                'verbose_name_plural': 'Изображение проекта',
                'db_table': 'project_image',
            },
        ),
        migrations.CreateModel(
            name='ProjectSmeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(blank=True, null=True, upload_to='project_files/', verbose_name='Файл проекта')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='admin_account.project', verbose_name='Проекта')),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файл проекта',
                'db_table': 'project_file',
            },
        ),
    ]
