# Generated by Django 5.1.2 on 2024-10-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0003_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmeta',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='project_files/', verbose_name='Файл проекта'),
        ),
    ]
