# Generated by Django 5.1.2 on 2024-11-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_account', '0004_alter_projectsmeta_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
    ]
